In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df= pd.read_csv('Video Games Sales.csv')

In [3]:
df

,index,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [4]:
df.drop('index', axis= 1, inplace= True)

In [5]:
df

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [6]:
df.set_index('Rank', inplace= True)

In [7]:
df

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...
1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [8]:
df.head()

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00

In [9]:
df[df['Game Title'].str.contains('Pokemon')]

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
11,Pokemon Gold / Silver Version,GB,1999,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10,89.00
20,Pokemon Diamond / Pearl Version,DS,2006,Role-Playing,Nintendo,6.32,4.34,6.04,1.35,18.05,90.00
23,Pokemon Ruby / Sapphire Version,GBA,2002,Role-Playing,Nintendo,6.06,3.90,5.38,0.50,15.85,86.00
27,Pokemon Yellow: Special Pikachu Edition,GB,1998,Role-Playing,Nintendo,5.89,5.04,3.12,0.59,14.64,88.00
28,Pokemon Black / White Version,DS,2010,Role-Playing,Nintendo,5.30,2.81,5.64,0.89,14.64,85.88
39,Pokemon Heart Gold / Soul Silver Version,DS,2009,Role-Playing,Nintendo,4.20,2.59,3.96,0.77,11.51,87.81
46,Pokemon FireRed / LeafGreen Version,GBA,2004,Role-Playing,Nintendo,4.34,2.65,3.15,0.35,10.49,87.00
75,Pokemon Platinum Version,DS,2008,Role-Playing,Nintendo,2.68,1.62,2.69,0.53,7.52,89.00
94,Pokemon Emerald Version,GBA,2004,Role-Playing,Nintendo,2.57,1.58,2.06,0.21,6.41,86.00
95,Pokemon Crystal Version,GB,2000,Role-Playing,Nintendo,2.55,1.56,1.29,0.99,6.39,88.00
96,Pokemon Black / White Version 2,DS,2012,Role-Playing,Nintendo,1.99,1.09,2.97,0.34,6.38,81.31
130,Pokemon Stadium,N64,1999,Strategy,Nintendo,3.18,1.24,0.94,0.09,5.45,73.00
138,Pokemon Pinball,GB,1999,Misc,Nintendo,3.02,1.12,1.01,0.16,5.31,80.00
171,Pokemon Mystery Dungeon: Explorers of Time / D...,DS,2007,Role-Playing,Nintendo,1.81,1.16,1.54,0.37,4.89,84.00
267,Pokemon Trading Card Game,GB,1998,Strategy,Nintendo,1.49,0.73,1.38,0.10,3.70,78.00
276,Pokemon Snap,N64,1999,Simulation,Nintendo,2.23,0.68,0.66,0.06,3.63,78.00
431,Pokemon Stadium 2,N64,2000,Strategy,Nintendo,1.02,0.36,1.13,0.23,2.73,80.00
477,Pokemon Colosseum,GC,2003,Role-Playing,Nintendo,1.21,0.57,0.70,0.07,2.54,78.00
568,Pokemon Ranger: Shadows of Almia,DS,2008,Role-Playing,Nintendo,0.93,0.52,0.62,0.18,2.25,82.00
615,Pokemon Ranger,DS,2006,Role-Playing,Nintendo,1.26,0.01,0.73,0.11,2.11,79.00
638,Pokemon Mystery Dungeon: Red Rescue Team,GBA,2005,Role-Playing,Nintendo,0.71,0.52,0.74,0.08,2.06,80.00
672,Pokemon Mystery Dungeon: Blue Rescue Team,DS,2005,Role-Playing,Nintendo,1.13,0.01,0.83,0.00,1.98,64.01
930,Pokemon Pinball: Ruby & Sapphire,GBA,2003,Misc,Nintendo,0.68,0.38,0.44,0.05,1.56,79.00
957,Pokemon Mystery Dungeon: Explorers of Sky,DS,2009,Role-Playing,Nintendo,0.54,0.42,0.44,0.12,1.52,86.00
963,Pokemon Battle Revolution,Wii,2006,Role-Playing,Nintendo,0.77,0.33,0.30,0.12,1.52,53.19
1224,Pokemon XD: Gale of Darkness,GC,2005,Role-Playing,Nintendo,0.71,0.19,0.31,0.03,1.25,81.00
1264,Pokemon Ranger: Guardian Signs,DS,2010,Role-Playing,Nintendo,0.45,0.13,0.58,0.06,1.22,87.00
1402,Pokemon Mystery Dungeon: Red Rescue Team (US w...,GBA,2005,Role-Playing,Nintendo,0.81,0.30,0.00,0.02,1.13,80.00
1575,Pokemon Rumble Blast,3DS,2011,Action,Nintendo,0.41,0.20,0.34,0.06,1.01,77.00
1794,Pokemon Card GB2: GRdan Sanjou,GB,2001,Strategy,Nintendo,0.00,0.00,0.89,0.00,0.89,78.00

In [10]:
df.isna().sum()

Game Title       0
Platform         0
Year             0
Genre            0
Publisher        0
North America    0
Europe           0
Japan            0
Rest of World    0
Global           0
Review           0
dtype: int64

In [11]:
df.describe()

,Year,North America,Europe,Japan,Rest of World,Global,Review
count,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000
mean,2003.769271,1.258789,0.706675,0.317493,0.206471,2.489240,79.038977
std,5.871681,1.956560,1.148904,0.724945,0.343093,3.563159,10.616899
min,1983.000000,0.000000,0.000000,0.000000,0.000000,0.830000,30.500000
25%,2000.500000,0.510000,0.230000,0.000000,0.060000,1.110000,74.000000
50%,2005.000000,0.810000,0.440000,0.020000,0.130000,1.530000,81.000000
75%,2008.000000,1.375000,0.810000,0.300000,0.220000,2.540000,86.230000
max,2012.000000,40.430000,28.390000,7.200000,8.540000,81.120000,97.000000

In [12]:
df.to_csv('Video_Games_Sales_new.csv')

In [13]:
df2= pd.read_csv('Video_Games_Sales_new.csv')

In [14]:
df2

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [15]:
df2['Game Title'].str.contains('wii', case= False)

0        True
1       False
2        True
3        True
4       False
        ...
1902    False
1903    False
1904    False
1905    False
1906    False
Name: Game Title, Length: 1907, dtype: bool

In [16]:
if (df2['Game Title'].str.contains('wii', case= False) == True).any():
    print(df2[df2['Game Title'].str.contains('wii', case= False)])

      Rank                         Game Title Platform  Year      Genre  \
0        1                         Wii Sports      Wii  2006     Sports
2        3                     Mario Kart Wii      Wii  2008     Racing
3        4                  Wii Sports Resort      Wii  2009     Sports
6        7                           Wii Play      Wii  2006       Misc
8        9          New Super Mario Bros. Wii      Wii  2009   Platform
11      12                            Wii Fit      Wii  2007     Sports
13      14                       Wii Fit Plus      Wii  2009     Sports
64      65                          Wii Party      Wii  2010       Misc
260    261      Big Brain Academy: Wii Degree      Wii  2007       Misc
337    338                          Wii Music      Wii  2008       Misc
1323  1324  PokePark Wii: Pikachu's Adventure      Wii  2009  Adventure

     Publisher  North America  Europe  Japan  Rest of World  Global  Review
0     Nintendo          40.43   28.39   3.77           8.54   81.12   76.28
2     Nintendo          14.50   12.22   3.63           3.21   33.55   82.07
3     Nintendo          14.82   10.51   3.18           3.01   31.52   82.65
6     Nintendo          13.83    9.11   2.93           2.84   28.71   61.64
8     Nintendo          13.35    6.48   4.66           2.25   26.75   88.18
11    Nintendo           8.91    8.15   3.60           2.08   22.74   81.20
13    Nintendo           8.82    7.94   2.53           1.86   21.15   80.83
64    Nintendo           1.68    3.28   2.46           0.67    8.09   70.44
260   Nintendo           1.03    1.87   0.41           0.42    3.72   70.26
337   Nintendo           1.33    1.09   0.46           0.31    3.19   64.34
1323  Nintendo           0.50    0.19   0.42           0.07    1.18   78.00

In [17]:
df2[df2['Game Title'].str.contains('wii', case= False)]

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
6,7,Wii Play,Wii,2006,Misc,Nintendo,13.83,9.11,2.93,2.84,28.71,61.64
8,9,New Super Mario Bros. Wii,Wii,2009,Platform,Nintendo,13.35,6.48,4.66,2.25,26.75,88.18
11,12,Wii Fit,Wii,2007,Sports,Nintendo,8.91,8.15,3.60,2.08,22.74,81.20
13,14,Wii Fit Plus,Wii,2009,Sports,Nintendo,8.82,7.94,2.53,1.86,21.15,80.83
64,65,Wii Party,Wii,2010,Misc,Nintendo,1.68,3.28,2.46,0.67,8.09,70.44
260,261,Big Brain Academy: Wii Degree,Wii,2007,Misc,Nintendo,1.03,1.87,0.41,0.42,3.72,70.26
337,338,Wii Music,Wii,2008,Misc,Nintendo,1.33,1.09,0.46,0.31,3.19,64.34
1323,1324,PokePark Wii: Pikachu's Adventure,Wii,2009,Adventure,Nintendo,0.50,0.19,0.42,0.07,1.18,78.00

In [18]:
df2['Platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'PS2', 'SNES', 'X360', 'GBA', 'PS3',
       'N64', 'PC', 'PS', 'XB', '3DS', 'PSP', 'GC', 'GEN', 'DC', 'SAT',
       'WiiU', 'SCD', 'PSV'], dtype=object)

In [19]:
df2['Publisher'].sort_values(ascending= False).unique()

array(['id Software', 'Westwood Studios',
       'Warner Bros. Interactive Entertainment', 'Vivendi Games',
       'Virgin Interactive', 'Video System', 'Valve Software', 'Valve',
       'Universal Interactive', 'Ubisoft', 'Tomy Corporation', 'Titus',
       'Tecmo Koei', 'TalonSoft', 'Take-Two Interactive', 'THQ',
       'TDK Mediactive', 'Success', 'Square Enix', 'Square EA', 'Square',
       'SouthPeak Games', 'Sony Online Entertainment',
       'Sony Computer Entertainment', 'Sega', 'Sammy Corporation', 'SCi',
       'Russel', 'Rising Star Games', 'RedOctane',
       'Red Storm Entertainment', 'Red Orb', 'Rage Software', 'RTL',
       'Psygnosis', 'Play It', 'Pinnacle', 'Pacific Century Cyber Works',
       'Ocean', 'Nintendo', 'Natsume', 'Namco Bandai Games', 'NCSoft',
       'Mindscape', 'Midway Games', 'Microsoft Game Studios',
       'Microprose', 'Maxis', 'Mastertronic', 'Majesco Entertainment',
       'MTV Games', 'LucasArts', 'Level 5',
       'Konami Digital Entertainment', 'Koch Media', 'JVC', 'Infogrames',
       'Hudson Soft', 'Havas Interactive', 'Hasbro Interactive',
       'Gotham Games', 'Global Star', 'GameBank', 'GT Interactive', 'GSP',
       'Fox Interactive', 'Enix Corporation', 'Empire Interactive',
       'Electronic Arts', 'Eidos Interactive',
       'Disney Interactive Studios', 'Deep Silver', 'D3Publisher',
       'Crystal Dynamics', 'Crave Entertainment', 'Codemasters',
       'City Interactive', 'Capcom', 'CTO SpA', 'Black Label Games',
       'Bethesda Softworks', 'Banpresto', 'Atari', 'Arena Entertainment',
       'Agetec', 'Activision', 'Accolade', 'Acclaim Entertainment',
       'ASCII Entertainment', 'ASC Games', '989 Studios', '505 Games',
       '3DO'], dtype=object)

In [20]:
df2['Year'].sort_values(ascending= False).unique()

array([2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002,
       2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991,
       1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983], dtype=int64)

In [21]:
df2.dtypes

Rank               int64
Game Title        object
Platform          object
Year               int64
Genre             object
Publisher         object
North America    float64
Europe           float64
Japan            float64
Rest of World    float64
Global           float64
Review           float64
dtype: object

In [22]:
qwe= df2[(df2['Platform'] == 'DS') & (df2['Year'] == 2006) & (df2['Genre'] == 'Platform')]

In [23]:
qwe

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
5,6,New Super Mario Bros.,DS,2006,Platform,Nintendo,10.85,8.87,6.48,2.88,29.08,90.00
440,441,Yoshi's Island DS,DS,2006,Platform,Nintendo,1.41,0.04,1.10,0.14,2.69,86.00
715,716,Kirby Squeak Squad,DS,2006,Platform,Nintendo,0.77,0.01,1.05,0.08,1.91,72.24

In [24]:
year= df['Year'].sort_values(ascending= False).unique()

In [25]:
type(year)

numpy.ndarray

In [26]:
year2= year.tolist()

In [27]:
type(year2)

list

In [28]:
platform= df2['Platform'].sort_values(ascending= True).unique()

In [29]:
type(platform)

numpy.ndarray

In [30]:
df2.columns

Index(['Rank', 'Game Title', 'Platform', 'Year', 'Genre', 'Publisher',
       'North America', 'Europe', 'Japan', 'Rest of World', 'Global',
       'Review'],
      dtype='object')

In [31]:
type(df2.groupby('Year').count())

pandas.core.frame.DataFrame

In [32]:
type(df.columns)

pandas.core.indexes.base.Index

In [33]:
df2.iloc[: , 2: 6].columns

Index(['Platform', 'Year', 'Genre', 'Publisher'], dtype='object')

In [34]:
df2.sort_values('Review', ascending= False).head(10)

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
73,74,The Legend of Zelda: Ocarina of Time,N64,1998,Adventure,Nintendo,4.10,1.89,1.45,0.16,7.60,97.00
821,822,The Orange Box,X360,2007,Shooter,Electronic Arts,1.04,0.48,0.02,0.17,1.71,96.36
411,412,Metroid Prime,GC,2002,Shooter,Nintendo,1.96,0.67,0.10,0.09,2.82,96.35
78,79,Tekken 3,PS,1998,Fighting,Sony Computer Entertainment,3.27,2.22,1.40,0.29,7.16,96.30
461,462,BioShock,X360,2007,Shooter,Take-Two Interactive,1.46,0.81,0.05,0.26,2.58,96.12
264,265,Batman: Arkham Asylum,PS3,2009,Action,Eidos Interactive,1.95,1.16,0.05,0.54,3.71,96.09
838,839,Resident Evil 4,GC,2005,Action,Capcom,0.98,0.42,0.22,0.06,1.69,95.83
278,279,Resident Evil 4,PS2,2005,Action,Capcom,2.08,0.83,0.46,0.25,3.62,95.77
378,379,Mass Effect 2,X360,2010,Role-Playing,Electronic Arts,1.92,0.75,0.03,0.28,2.97,95.69
92,93,Halo: Combat Evolved,XB,2001,Shooter,Microsoft Game Studios,4.98,1.30,0.08,0.07,6.43,95.54

In [35]:
df2['Year'].sum()

3821188

In [36]:
df2.index

RangeIndex(start=0, stop=1907, step=1)

In [37]:
df2

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [38]:
df2.drop('Rank', axis= 1, inplace=True)

In [39]:
df2

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...
1902,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [40]:
df2.columns= ['게임 제목', '플랫폼', '출시연도', '장르', '배급사', '북미 판매량', '유럽 판매량', '일본 판매량', '그 외 국가 판매량', '전세계 판매량', '리뷰 점수']

In [41]:
df2

,게임 제목,플랫폼,출시연도,장르,배급사,북미 판매량,유럽 판매량,일본 판매량,그 외 국가 판매량,전세계 판매량,리뷰 점수
0,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...
1902,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [42]:
df2.to_csv('Video_Games_Sales_new2.csv')

In [43]:
df3= pd.read_csv('Video_Games_Sales_new2.csv', index_col=0)

In [44]:
df3

,게임 제목,플랫폼,출시연도,장르,배급사,북미 판매량,유럽 판매량,일본 판매량,그 외 국가 판매량,전세계 판매량,리뷰 점수
0,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...
1902,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [47]:
df3.index[0]

0