In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [16]:
df= pd.read_csv('Video Games Sales.csv')

In [17]:
df

,index,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [20]:
df.drop('index', axis= 1, inplace= True)

In [21]:
df

,Rank,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
0,1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
4,5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1902,1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1903,1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1904,1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1905,1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1906,1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [23]:
df.set_index('Rank', inplace= True)

In [24]:
df

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00
...,...,...,...,...,...,...,...,...,...,...,...
1903,Lizzie McGuire 2: Lizzie Diaries,GBA,2004,Action,Disney Interactive Studios,0.60,0.22,0.00,0.01,0.83,55.00
1904,Xenoblade Chronicles,Wii,2010,Role-Playing,Nintendo,0.39,0.22,0.16,0.07,0.83,91.74
1905,SingStar Abba,PS3,2008,Misc,Sony Computer Entertainment,0.25,0.44,0.00,0.14,0.83,73.00
1906,FIFA Soccer World Championship,PS2,2000,Sports,Electronic Arts,0.27,0.21,0.28,0.07,0.83,73.00
1907,WWE SmackDown vs. Raw 2011,X360,2010,Fighting,THQ,0.42,0.32,0.00,0.09,0.83,82.00

In [26]:
df.head()

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
1,Wii Sports,Wii,2006,Sports,Nintendo,40.43,28.39,3.77,8.54,81.12,76.28
2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,91.00
3,Mario Kart Wii,Wii,2008,Racing,Nintendo,14.50,12.22,3.63,3.21,33.55,82.07
4,Wii Sports Resort,Wii,2009,Sports,Nintendo,14.82,10.51,3.18,3.01,31.52,82.65
5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,88.00

In [27]:
df[df['Game Title'].str.contains('Pokemon')]

,Game Title,Platform,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global,Review
Rank,,,,,,,,,,,
11,Pokemon Gold / Silver Version,GB,1999,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10,89.00
20,Pokemon Diamond / Pearl Version,DS,2006,Role-Playing,Nintendo,6.32,4.34,6.04,1.35,18.05,90.00
23,Pokemon Ruby / Sapphire Version,GBA,2002,Role-Playing,Nintendo,6.06,3.90,5.38,0.50,15.85,86.00
27,Pokemon Yellow: Special Pikachu Edition,GB,1998,Role-Playing,Nintendo,5.89,5.04,3.12,0.59,14.64,88.00
28,Pokemon Black / White Version,DS,2010,Role-Playing,Nintendo,5.30,2.81,5.64,0.89,14.64,85.88
39,Pokemon Heart Gold / Soul Silver Version,DS,2009,Role-Playing,Nintendo,4.20,2.59,3.96,0.77,11.51,87.81
46,Pokemon FireRed / LeafGreen Version,GBA,2004,Role-Playing,Nintendo,4.34,2.65,3.15,0.35,10.49,87.00
75,Pokemon Platinum Version,DS,2008,Role-Playing,Nintendo,2.68,1.62,2.69,0.53,7.52,89.00
94,Pokemon Emerald Version,GBA,2004,Role-Playing,Nintendo,2.57,1.58,2.06,0.21,6.41,86.00
95,Pokemon Crystal Version,GB,2000,Role-Playing,Nintendo,2.55,1.56,1.29,0.99,6.39,88.00
96,Pokemon Black / White Version 2,DS,2012,Role-Playing,Nintendo,1.99,1.09,2.97,0.34,6.38,81.31
130,Pokemon Stadium,N64,1999,Strategy,Nintendo,3.18,1.24,0.94,0.09,5.45,73.00
138,Pokemon Pinball,GB,1999,Misc,Nintendo,3.02,1.12,1.01,0.16,5.31,80.00
171,Pokemon Mystery Dungeon: Explorers of Time / D...,DS,2007,Role-Playing,Nintendo,1.81,1.16,1.54,0.37,4.89,84.00
267,Pokemon Trading Card Game,GB,1998,Strategy,Nintendo,1.49,0.73,1.38,0.10,3.70,78.00
276,Pokemon Snap,N64,1999,Simulation,Nintendo,2.23,0.68,0.66,0.06,3.63,78.00
431,Pokemon Stadium 2,N64,2000,Strategy,Nintendo,1.02,0.36,1.13,0.23,2.73,80.00
477,Pokemon Colosseum,GC,2003,Role-Playing,Nintendo,1.21,0.57,0.70,0.07,2.54,78.00
568,Pokemon Ranger: Shadows of Almia,DS,2008,Role-Playing,Nintendo,0.93,0.52,0.62,0.18,2.25,82.00
615,Pokemon Ranger,DS,2006,Role-Playing,Nintendo,1.26,0.01,0.73,0.11,2.11,79.00
638,Pokemon Mystery Dungeon: Red Rescue Team,GBA,2005,Role-Playing,Nintendo,0.71,0.52,0.74,0.08,2.06,80.00
672,Pokemon Mystery Dungeon: Blue Rescue Team,DS,2005,Role-Playing,Nintendo,1.13,0.01,0.83,0.00,1.98,64.01
930,Pokemon Pinball: Ruby & Sapphire,GBA,2003,Misc,Nintendo,0.68,0.38,0.44,0.05,1.56,79.00
957,Pokemon Mystery Dungeon: Explorers of Sky,DS,2009,Role-Playing,Nintendo,0.54,0.42,0.44,0.12,1.52,86.00
963,Pokemon Battle Revolution,Wii,2006,Role-Playing,Nintendo,0.77,0.33,0.30,0.12,1.52,53.19
1224,Pokemon XD: Gale of Darkness,GC,2005,Role-Playing,Nintendo,0.71,0.19,0.31,0.03,1.25,81.00
1264,Pokemon Ranger: Guardian Signs,DS,2010,Role-Playing,Nintendo,0.45,0.13,0.58,0.06,1.22,87.00
1402,Pokemon Mystery Dungeon: Red Rescue Team (US w...,GBA,2005,Role-Playing,Nintendo,0.81,0.30,0.00,0.02,1.13,80.00
1575,Pokemon Rumble Blast,3DS,2011,Action,Nintendo,0.41,0.20,0.34,0.06,1.01,77.00
1794,Pokemon Card GB2: GRdan Sanjou,GB,2001,Strategy,Nintendo,0.00,0.00,0.89,0.00,0.89,78.00

In [28]:
df.isna().sum()

Game Title       0
Platform         0
Year             0
Genre            0
Publisher        0
North America    0
Europe           0
Japan            0
Rest of World    0
Global           0
Review           0
dtype: int64

In [29]:
df.describe()

,Year,North America,Europe,Japan,Rest of World,Global,Review
count,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000
mean,2003.769271,1.258789,0.706675,0.317493,0.206471,2.489240,79.038977
std,5.871681,1.956560,1.148904,0.724945,0.343093,3.563159,10.616899
min,1983.000000,0.000000,0.000000,0.000000,0.000000,0.830000,30.500000
25%,2000.500000,0.510000,0.230000,0.000000,0.060000,1.110000,74.000000
50%,2005.000000,0.810000,0.440000,0.020000,0.130000,1.530000,81.000000
75%,2008.000000,1.375000,0.810000,0.300000,0.220000,2.540000,86.230000
max,2012.000000,40.430000,28.390000,7.200000,8.540000,81.120000,97.000000

In [31]:
df.to_csv('Video_Games_Sales_new.csv')

In [35]:
df2= pd.read_csv('Video_Games_Sales_new.csv', index_col= 0)

In [36]:
df2.describe()

,Year,North America,Europe,Japan,Rest of World,Global,Review
count,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000,1907.000000
mean,2003.769271,1.258789,0.706675,0.317493,0.206471,2.489240,79.038977
std,5.871681,1.956560,1.148904,0.724945,0.343093,3.563159,10.616899
min,1983.000000,0.000000,0.000000,0.000000,0.000000,0.830000,30.500000
25%,2000.500000,0.510000,0.230000,0.000000,0.060000,1.110000,74.000000
50%,2005.000000,0.810000,0.440000,0.020000,0.130000,1.530000,81.000000
75%,2008.000000,1.375000,0.810000,0.300000,0.220000,2.540000,86.230000
max,2012.000000,40.430000,28.390000,7.200000,8.540000,81.120000,97.000000